name: midnight-launcher
version: '0.0.0'
summary: Midnight launcher is a minecraft client and launcher for minecraft!! (original or pirate)
description: Midnight launcher is a minecraft client and launcher for minecraft!! (original or pirate)

🔧 Functions
Ultra Voice-Chat:
Our Own Server Can Connect Up To 100 Players In Same Server Talking To Each Other!!

Optimization:
Midnight launcher is light and fast in low-end-pcs!! (one time that the client creator has a potato pc...)

Client Tag:
In game everyone using midnight client have a logo before their name that everyone(using the same client) Can see!!

Midnight HUD:
Keystrokes, fps, armor hud and more, that can be moved to any place of the screen, be customized using midnight themes or simply turned off...

💻 Requirements:
- 1.8ghz Cpu
- 2gb Ram
 Geforce 7200gs(opcional)

grade: devel
confinement: devmode
parts:
  my-part:
    plugin: nil
