name: midnight-launcher
version: '0.0.0'
summary: Midnight launcher is a minecraft client and launcher for minecraft!! (original or pirate)
description: Midnight launcher is a minecraft client and launcher for minecraft!! (original or pirate)

grade: devel
confinement: devmode
parts:
  my-part:
    plugin: nil
